# Generated by Django 4.2.1 on 2023-06-07 08:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_subscription_subscription_unique_user_follow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["id"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
